### ISSUE TITLE
Jupyter kernel dying when running a 3x2pt forecast with A_s and m_nu

### ISSUE THREAD

**Issue by bruno-moraes** [LSSTDESC/augur#62]
When attempting a 3x2pt forecast with neutrino masses m_nu, it runs and completes when the sigma8 parameter is used. If A_s is used instead, the Jupyter kernel dies after a few seconds when trying to calculate the Fisher matrix.

I have not tested running from the command line nor with other parameter combinations. I will attempt to solve this by using A_s*10**9 instead of A_s.

**Comment by bruno-moraes** [comment]
I will work on this now.

**Comment by bruno-moraes** [comment]
@fjaviersanchez , I could pinpoint more or less where the error is, but this is something I never fixed before. I assume it's numerical instabilities in the derivatives due to the small values of A_s compared to the other parameters. I won't be able to solve it now.

**Comment by fjaviersanchez** [comment]
Thank you for checking and identifying the issue! I think this can be potentially solved when we add the stem derivative method. One potential solution is to normalize all parameters internally for the derivatives and then change back or change the step size dynamically, but will check first if the easy fix works.

**Comment by fjaviersanchez** [comment]
I included a way to normalize the parameters if you pass parameter bounds in the input configuration file (à la cosmosis) in #68. If you want to take a look at the latest master branch and retry. You will need to modify the `test.yaml` file changing `var_pars` to a `parameters` section that might look like:

```
fisher:
    # var_pars: ['Omega_c', 'sigma8', 'n_s', 'w0', 'wa', 'Omega_b', 'h', 'ia_bias', 'lens0_mag_bias', 'lens1_mag_bias', 'lens2_mag_bias', 'lens3_mag_bias', 'lens4_mag_bias', 'lens0_bias', 'lens1_bias', 'lens2_bias', 'lens3_bias', 'lens4_bias', 'src0_delta_z', 'src1_delta_z', 'src2_delta_z', 'src3_delta_z', 'src4_delta_z', 'lens0_delta_z', 'lens1_delta_z', 'lens2_delta_z', 'lens3_delta_z', 'lens4_delta_z']
    parameters:  # TODO: For now priors are ignored
         Omega_c: [0.06, 0.2664315, 0.46]
         sigma8: [0.03, 0.831, 1.2]
         n_s: [0.85, 0.9645, 1.10]
         w0: [-3.0, -1.0, -0.33]
         wa: [-3.0, 0.0, 3.0]
         Omega_b: [0.03, 0.0491685, 0.07]
         h: [0.5, 0.6727, 0.8]
        #  ia_bias: [-5.0, 1.0, 5.0]
        #  lens0_mag_bias: [-10, 0, 10]
        #  lens1_mag_bias: [-10, 0, 10]
        #  lens2_mag_bias: [-10, 0, 10]
        #  lens3_mag_bias: [-10, 0, 10]
        #  lens4_mag_bias: [-10, 0, 10]
        #  lens0_bias: [0.8, 1.23885511, 2.5]
        #  lens1_bias: [0.8, 1.3781005, 2.5]
        #  lens2_bias: [0.8, 1.52472019, 2.5]
        #  lens3_bias: [0.8, 1.67665752, 2.5]
        #  lens4_bias: [0.8, 1.83243479, 2.5]
        #  src0_delta_z: [-10, 0, 10]
        #  src1_delta_z: [-10, 0, 10]
        #  src2_delta_z: [-10, 0, 10]
        #  src3_delta_z: [-10, 0, 10]
        #  src4_delta_z: [-10, 0, 10]
        #  lens0_delta_z: [-10, 0, 10]
        #  lens1_delta_z: [-10, 0, 10]
        #  lens2_delta_z: [-10, 0, 10]
        #  lens3_delta_z: [-10, 0, 10]
        #  lens4_delta_z: [-10, 0, 10]
```

**Comment by fjaviersanchez** [comment]
I think this has been solved in the current version. Could you please confirm @bruno-moraes?

**Comment by arthurmloureiro** [comment]
Retested this on the current stack (firecrown 1.16.0, augur 1.2.4 at `f8ab7cf`, pyccl 3.3.6,
camb 1.6.5, sacc 2.4, python 3.12). **It still reproduces, and the cause is not `A_s`.** It is
the step size.

## What actually happens

`derivkit`'s `resolve_spacing` treats `base_abs` as an absolute **floor** on the half-width:

```python
h = frac * abs(float(x0))     # '1%' of x0
return float(max(h, floor))   # floor = base_abs
```

augur's derivkit defaults (`analyze.py:576-582`, and every example config) set
`base_abs: 1.e-3`. For a parameter of order unity that floor never binds. For `A_s = 2.1e-9` it
is six orders of magnitude larger than the parameter itself:

| parameter | x0 | 1% of x0 | halfwidth actually used | sampled range |
|---|---|---|---|---|
| `Omega_c` | 0.2664 | 2.664e-3 | 2.664e-3 | [0.2637, 0.2691] |
| `h` | 0.6727 | 6.727e-3 | 6.727e-3 | [0.6660, 0.6794] |
| `sigma8` | 0.831 | 8.31e-3 | 8.31e-3 | [0.8227, 0.8393] |
| **`A_s`** | **2.1e-9** | **2.1e-11** | **1e-3 (the floor)** | **[-1.0e-3, +1.0e-3]** |

So the derivative grid steps `A_s` to large **negative** values. CAMB returns a non-positive
P(k), `np.log` produces NaN, and you get exactly the symptom in this issue:

```
pyccl/boltzmann.py:177: RuntimeWarning: invalid value encountered in log
  ln_p_k_and_z[i, :] = np.log(pk[sind, :])
```

Same line and function as the `boltzmann.py:170` in the original report.

## `numdifftools` has the same bug

augur passes the config `step` straight to `nd.Jacobian(step=...)`, where a scalar step is
**absolute** and applies to every parameter alike. Instrumenting the sampled points for
`step: 1e-2` at `x0 = [Omega_c, A_s, h]`:

```
Omega_c  min=0.2564     max=0.2764     n_negative=0
A_s      min=-0.01      max=0.01       n_negative=1
h        min=0.6627     max=0.6827     n_negative=0
```

`A_s` is driven negative again. The SRD examples use `step: 1e-4`, which is smaller but still
five orders too large for `A_s`. That is most likely the path this issue was originally hit on.

## Verified fix

One line in the config — `base_abs: 1.e-12` instead of `1.e-3`:

```
[   21.7s] derivatives (3, 410) all-finite=True
Fisher finite : True
eigenvalues   : [1.18098392e+04 9.40243235e+05 5.02490265e+22]
sigma(A_s)    : 5.138e-11
RESULT: A_s Fisher COMPLETED in 21.7s via derivkit
```

Zero NaN warnings; the same run with `base_abs: 1.e-3` dies within 30 s. The new floor is inert
for every other parameter, since their relative steps (~1e-3 … 1e-2) already exceed it.

Two other routes work as well: `norm_step: True` (`analyze.py:181-190`) makes a scalar step
relative to each parameter's `fisher.parameters` bounds — though it is explicitly forced off for
derivkit at `analyze.py:540-543`; and varying `ln(10^10 A_s) ~ 3.045` instead of `A_s`, which is
the standard convention and makes every step-size heuristic behave.

## The bug worth fixing

Not "`A_s` breaks derivatives" but: **augur applies a single absolute step size, or a single
absolute floor, across parameters spanning nine orders of magnitude.** Any amplitude-like
parameter hits this; `A_s` is just the one small enough to make it fatal rather than merely
inaccurate.

The fix is per-parameter step scaling — derive the step from each parameter's own magnitude, or
let `base_abs` be specified per parameter rather than globally. #151 ("Allow `norm_step` to be
set in config") is already in this area, so it may be the natural place for it rather than a
separate change.

Happy to send a PR if that is useful, though it overlaps enough with #151 that it is probably
better folded in there.
